Outbound-company/Controllers/AsteriskController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Outbound_company.Services.Interfaces;

namespace Outbound_company.Controllers
{
    [Authorize]
    public class AsteriskController : Controller
    {
        private readonly IAsteriskStatusService _asteriskStatusService;

        public AsteriskController(IAsteriskStatusService asteriskStatusService)
        {
            _asteriskStatusService = asteriskStatusService;
        }

        [HttpGet]
        public IActionResult GetStatus()
        {
            var status = _asteriskStatusService.GetStatus();
            var result = new
            {
                AsteriskStatus = status.Status
            };
            return Json(result);
        }
    }
}

Outbound-company/Controllers/CallController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Outbound_company.Models;
using Serilog;
using System.Net.Http.Headers;
using System.Text;

namespace Outbound_company.Controllers
{
    [Authorize]
    public class CallController : Controller
    {
        private readonly AsteriskSettings _asteriskSettings;
        private static readonly HttpClient client = new HttpClient();
        public CallController(IOptions<AsteriskSettings> asteriskSettings)
        {
            _asteriskSettings = asteriskSettings.Value;
        }
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> MakeCall(string typeOfTrunk, string phoneNumber, string channel, string extension, string context, string callerId)
        {
            try
            {
                var requestUri = $"http://{_asteriskSettings.Url}/ari/channels";
                var authToken = Convert.ToBase64String(Encoding.ASCII.GetBytes($"{_asteriskSettings.Username}:{_asteriskSettings.Password}"));

                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", authToken);

                var jsonContent = new
                {
                    endpoint = $"{typeOfTrunk}/{phoneNumber}@{channel}",
                    extension = extension,
                    context = context,
                    callerId = callerId
                };

                var content = new StringContent(Newtonsoft.Json.JsonConvert.SerializeObject(jsonContent), Encoding.UTF8, "application/json");

                var response = await client.PostAsync(requestUri, content);

                if (response.IsSuccessStatusCode)
                {
                    ViewBag.Message = "Call initiated successfully!";
                    Log.Information($"Test call. Call initiated successfully to {phoneNumber} using trunk {typeOfTrunk}/{channel}.");

                }
                else
                {
                    ViewBag.Message = $"Failed to initiate call. Status code: {response.StatusCode}";
                    Log.Warning($"Failed to initiate call to {phoneNumber}. Status code: {response.StatusCode}");
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message = $"Error: {ex.Message}";
                Log.Error(ex, $"Error initiating call to {phoneNumber} using trunk {typeOfTrunk}/{channel}.");
            }

            return View("Index");
        }
    }
}

Outbound-company/Controllers/CompaniesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Outbound_company.Models;
using Outbound_company.Services.Interfaces;
using Serilog;

namespace Outbound_company.Controllers
{
    [Authorize]
    public class CompaniesController : Controller
    {

        private ICompaniesService _companiesService;
        private INumberService _numberService;
        public CompaniesController(ICompaniesService companiesService, INumberService numberService)
        {
            _companiesService = companiesService ?? throw new ArgumentNullException(nameof(companiesService));
            _numberService = numberService ?? throw new ArgumentNullException( nameof(numberService));
        }

        public async Task<IActionResult> Index()
        {
            return View(await _companiesService.GetAllCompaniesAsync());
        }
        public async Task<IActionResult> Create()
        {
            ViewBag.NumberPools = new SelectList(await _numberService.GetAllNumberPoolsAsync(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Channel,Extension,Context,CallerId,NumberPoolId,TrunkType")] OutboundCompany outboundCompany)
        {
            if (ModelState.IsValid)
            {
                await _companiesService.InsertCompanyAsync(outboundCompany);
                Log.Information($"Company {outboundCompany.Name} created successfully.");
                return RedirectToAction(nameof(Index));
            }
            Log.Warning("Failed to create company due to invalid model state.");
            return View(outboundCompany);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var outboundCompany = await _companiesService.GetCompanyByIdAsync(id);
            if (outboundCompany == null)
            {
                Log.Warning($"Company with ID {id} not found.");
                return NotFound();
            }
            ViewBag.NumberPools = new SelectList(await _numberService.GetAllNumberPoolsAsync(), "Id", "Name");
            return View(outboundCompany);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Channel,Extension,Context,CallerId")] OutboundCompany outboundCompany)
        {
            outboundCompany.Id = id;

            if (ModelState.IsValid)
            {
                try
                {
                    await _companiesService.UpdateCompanyAsync(outboundCompany);
                    Log.Information($"Company {outboundCompany.Name} updated successfully.");
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    Log.Error(ex, $"Concurrency error updating company with ID {id}.");
                    return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }
            Log.Warning($"Failed to update company {outboundCompany.Name} due to invalid model state.");
            return View(outboundCompany);
        }
        public async Task<IActionResult> Delete(int id)
        {
            var outboundCompany = await _companiesService.GetCompanyByIdAsync(id);
            if (outboundCompany == null)
            {
                Log.Warning($"Company with ID {id} not found.");
                return NotFound();
            }

            return View(outboundCompany);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _companiesService.DeleteCompanyAsync(id);
            Log.Information($"Company with ID {id} deleted successfully.");
            return RedirectToAction(nameof(Index));
        }

    }
}

Outbound-company/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Outbound_company.Models;
using Outbound_company.Services.Interfaces;
using Serilog;
using System.Security.Cryptography;
using System.Text;

namespace Outbound_company.Controllers
{
    [Authorize]
    [Authorize(Policy = "AdminOnly")]
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            var users = await _userService.GetAllAsync();
            return View(users);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(User user)
        {
            if (ModelState.IsValid)
            {
                await _userService.AddAsync(user);
                Log.Information($"User {user.UserName} created successfully.");
                return RedirectToAction(nameof(Index));
            }
            Log.Warning("Failed to create user. Model state is invalid.");
            return View(user);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var user = await _userService.GetByIdAsync(id);
            if (user == null)
            {
                Log.Warning($"User with ID {id} not found.");
                return NotFound();
            }
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, User user, string username, string password, int role)
        {
            var updateUser = await _userService.GetByIdAsync(id);
            if (id != user.Id || updateUser == null)
            {
                Log.Warning($"User with ID {id} not found or ID mismatch.");
                return NotFound();
            }

            try
            {
                if (!string.IsNullOrEmpty(username) && username != updateUser.UserName)
                {
                    updateUser.UserName = username;
                    Log.Information($"Username for user ID {id} updated to {username}.");
                }

                if (role != updateUser.Role)
                {
                    updateUser.Role = role;
                    Log.Information($"Role for user ID {id} updated to {role}.");
                }

                if (!string.IsNullOrEmpty(password))
                {
                    using (var sha256 = SHA256.Create())
                    {
                        var bytes = Encoding.UTF8.GetBytes(password);
                        var hash = sha256.ComputeHash(bytes);
                        updateUser.PasswordHash = Convert.ToBase64String(hash);
                    }
                    Log.Information($"Password for user ID {id} updated.");
                }

                await _userService.UpdateAsync(updateUser);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await UserExists(updateUser.Id))
                {
                    Log.Warning($"User with ID {updateUser.Id} not found during update.");
                    return NotFound();
                }
                else
                {
                    Log.Error($"Concurrency exception occurred while updating user ID {updateUser.Id}.");
                    throw;
                }
            }
            Log.Information($"User ID {updateUser.Id} updated successfully.");
            return RedirectToAction(nameof(Index));


        }

        public async Task<IActionResult> Delete(int id)
        {
            var user = await _userService.GetByIdAsync(id);
            if (user == null)
            {
                Log.Warning($"User with ID {id} not found.");
                return NotFound();
            }
            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _userService.DeleteAsync(id);
            Log.Information($"User ID {id} deleted successfully.");
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> UserExists(int id)
        {
            var user = await _userService.GetByIdAsync(id);
            return user != null;
        }
    }
}

Outbound-company/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Outbound_company</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Outbound_company.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Companies" asp-action="Index">Companies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NumberPools" asp-action="Index">Pools</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BlackListNumber" asp-action="Index">Black list</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Call" asp-action="Index">Phone</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                        }
                    </ul>
                    <div>
                    <form asp-controller="Account" asp-action="Logout" method="post" class="form-inline">
                        <button type="submit" class="btn btn-link nav-link text-dark">Logout</button>
                    </form>
                    </div>
                    <div id="asterisk-status" class="ml-auto">
                        <p>Status: <span id="status">@ViewBag.AsteriskStatus</span></p>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Outbound_company - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    @RenderSection("Scripts", required: false)
    <script>
        $(document).ready(function () {
            function updateStatus() {
                $.ajax({
                    url: '@Url.Action("GetStatus", "Asterisk")',
                    type: 'GET',
                    success: function (data) {
                        var statusText;
                        var statusColor;
                        switch (data.asteriskStatus) {
                            case 1:
                                statusText = "Online";
                                statusColor = "green";
                                break;
                            case 2:
                                statusText = "Offline";
                                statusColor = "red";
                                break;
                            default:
                                statusText = "Unknown";
                                statusColor = "black";
                                break;
                        }
                        console.log('Response asteriskStatus:', statusText);

                        $('#status').html(statusText).css('color', statusColor).addClass('bold');
                    }
                });
            }

            // Обновляем статус каждые 5 секунд
            setInterval(updateStatus, 1000);

            // Начальное обновление
            updateStatus();
        });
    </script>
</body>
</html>